export const GET_ARTISTS_PENDING = 'GET_ARTISTS_PENDING'
export const GET_ARTISTS_FULFILLED = 'GET_ARTISTS_FULFILLED'
export const GET_ARTISTS_REJECTED = 'GET_ARTISTS_REJECTED'
export const SAVE_COVER_IMAGE = 'SAVE_COVER_IMAGE'